insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980000, 0, 1998, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19989991, 0, 1998, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980100, 0, 1998, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980200, 0, 1998, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980300, 0, 1998, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19989992, 0, 1998, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980400, 0, 1998, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980500, 0, 1998, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980600, 0, 1998, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19989993, 0, 1998, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980700, 0, 1998, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980800, 0, 1998, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19980900, 0, 1998, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19989994, 0, 1998, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19981000, 0, 1998, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19981100, 0, 1998, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19981200, 0, 1998, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990000, 0, 1999, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19999991, 0, 1999, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990100, 0, 1999, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990200, 0, 1999, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990300, 0, 1999, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19999992, 0, 1999, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990400, 0, 1999, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990500, 0, 1999, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990600, 0, 1999, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19999993, 0, 1999, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990700, 0, 1999, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990800, 0, 1999, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19990900, 0, 1999, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19999994, 0, 1999, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19991000, 0, 1999, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19991100, 0, 1999, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (19991200, 0, 1999, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000000, 0, 2000, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20009991, 0, 2000, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000100, 0, 2000, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000200, 0, 2000, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000300, 0, 2000, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20009992, 0, 2000, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000400, 0, 2000, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000500, 0, 2000, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000600, 0, 2000, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20009993, 0, 2000, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000700, 0, 2000, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000800, 0, 2000, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20000900, 0, 2000, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20009994, 0, 2000, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20001000, 0, 2000, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20001100, 0, 2000, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20001200, 0, 2000, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010000, 0, 2001, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20019991, 0, 2001, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010100, 0, 2001, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010200, 0, 2001, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010300, 0, 2001, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20019992, 0, 2001, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010400, 0, 2001, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010500, 0, 2001, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010600, 0, 2001, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20019993, 0, 2001, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010700, 0, 2001, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010800, 0, 2001, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20010900, 0, 2001, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20019994, 0, 2001, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20011000, 0, 2001, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20011100, 0, 2001, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20011200, 0, 2001, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020000, 0, 2002, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20029991, 0, 2002, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020100, 0, 2002, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020200, 0, 2002, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020300, 0, 2002, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20029992, 0, 2002, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020400, 0, 2002, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020500, 0, 2002, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020600, 0, 2002, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20029993, 0, 2002, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020700, 0, 2002, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020800, 0, 2002, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20020900, 0, 2002, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20029994, 0, 2002, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20021000, 0, 2002, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20021100, 0, 2002, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20021200, 0, 2002, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030000, 0, 2003, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20039991, 0, 2003, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030100, 0, 2003, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030200, 0, 2003, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030300, 0, 2003, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20039992, 0, 2003, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030400, 0, 2003, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030500, 0, 2003, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030600, 0, 2003, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20039993, 0, 2003, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030700, 0, 2003, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030800, 0, 2003, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20030900, 0, 2003, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20039994, 0, 2003, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20031000, 0, 2003, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20031100, 0, 2003, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20031200, 0, 2003, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040000, 0, 2004, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20049991, 0, 2004, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040100, 0, 2004, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040200, 0, 2004, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040300, 0, 2004, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20049992, 0, 2004, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040400, 0, 2004, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040500, 0, 2004, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040600, 0, 2004, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20049993, 0, 2004, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040700, 0, 2004, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040800, 0, 2004, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20040900, 0, 2004, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20049994, 0, 2004, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20041000, 0, 2004, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20041100, 0, 2004, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20041200, 0, 2004, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050000, 0, 2005, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20059991, 0, 2005, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050100, 0, 2005, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050200, 0, 2005, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050300, 0, 2005, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20059992, 0, 2005, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050400, 0, 2005, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050500, 0, 2005, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050600, 0, 2005, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20059993, 0, 2005, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050700, 0, 2005, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050800, 0, 2005, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20050900, 0, 2005, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20059994, 0, 2005, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20051000, 0, 2005, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20051100, 0, 2005, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20051200, 0, 2005, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060000, 0, 2006, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20069991, 0, 2006, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060100, 0, 2006, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060200, 0, 2006, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060300, 0, 2006, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20069992, 0, 2006, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060400, 0, 2006, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060500, 0, 2006, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060600, 0, 2006, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20069993, 0, 2006, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060700, 0, 2006, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060800, 0, 2006, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20060900, 0, 2006, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20069994, 0, 2006, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20061000, 0, 2006, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20061100, 0, 2006, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20061200, 0, 2006, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070000, 0, 2007, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20079991, 0, 2007, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070100, 0, 2007, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070200, 0, 2007, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070300, 0, 2007, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20079992, 0, 2007, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070400, 0, 2007, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070500, 0, 2007, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070600, 0, 2007, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20079993, 0, 2007, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070700, 0, 2007, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070800, 0, 2007, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20070900, 0, 2007, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20079994, 0, 2007, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20071000, 0, 2007, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20071100, 0, 2007, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20071200, 0, 2007, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080000, 0, 2008, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20089991, 0, 2008, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080100, 0, 2008, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080200, 0, 2008, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080300, 0, 2008, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20089992, 0, 2008, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080400, 0, 2008, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080500, 0, 2008, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080600, 0, 2008, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20089993, 0, 2008, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080700, 0, 2008, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080800, 0, 2008, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20080900, 0, 2008, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20089994, 0, 2008, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20081000, 0, 2008, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20081100, 0, 2008, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20081200, 0, 2008, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090000, 0, 2009, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20099991, 0, 2009, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090100, 0, 2009, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090200, 0, 2009, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090300, 0, 2009, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20099992, 0, 2009, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090400, 0, 2009, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090500, 0, 2009, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090600, 0, 2009, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20099993, 0, 2009, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090700, 0, 2009, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090800, 0, 2009, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20090900, 0, 2009, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20099994, 0, 2009, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20091000, 0, 2009, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20091100, 0, 2009, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20091200, 0, 2009, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100000, 0, 2010, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20109991, 0, 2010, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100100, 0, 2010, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100200, 0, 2010, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100300, 0, 2010, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20109992, 0, 2010, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100400, 0, 2010, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100500, 0, 2010, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100600, 0, 2010, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20109993, 0, 2010, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100700, 0, 2010, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100800, 0, 2010, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20100900, 0, 2010, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20109994, 0, 2010, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20101000, 0, 2010, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20101100, 0, 2010, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20101200, 0, 2010, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');

/* Start - 6630 - расширение классификаторов 'период' до 2020 года  - feanor - 28.11.2007 */

insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110000, 0, 2011, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20119991, 0, 2011, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110100, 0, 2011, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110200, 0, 2011, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110300, 0, 2011, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20119992, 0, 2011, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110400, 0, 2011, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110500, 0, 2011, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110600, 0, 2011, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20119993, 0, 2011, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110700, 0, 2011, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110800, 0, 2011, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20110900, 0, 2011, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20119994, 0, 2011, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20111000, 0, 2011, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20111100, 0, 2011, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20111200, 0, 2011, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120000, 0, 2012, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20129991, 0, 2012, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120100, 0, 2012, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120200, 0, 2012, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120300, 0, 2012, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20129992, 0, 2012, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120400, 0, 2012, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120500, 0, 2012, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120600, 0, 2012, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20129993, 0, 2012, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120700, 0, 2012, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120800, 0, 2012, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20120900, 0, 2012, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20129994, 0, 2012, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20121000, 0, 2012, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20121100, 0, 2012, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20121200, 0, 2012, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130000, 0, 2013, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20139991, 0, 2013, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130100, 0, 2013, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130200, 0, 2013, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130300, 0, 2013, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20139992, 0, 2013, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130400, 0, 2013, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130500, 0, 2013, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130600, 0, 2013, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20139993, 0, 2013, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130700, 0, 2013, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130800, 0, 2013, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20130900, 0, 2013, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20139994, 0, 2013, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20131000, 0, 2013, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20131100, 0, 2013, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20131200, 0, 2013, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140000, 0, 2014, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20149991, 0, 2014, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140100, 0, 2014, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140200, 0, 2014, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140300, 0, 2014, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20149992, 0, 2014, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140400, 0, 2014, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140500, 0, 2014, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140600, 0, 2014, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20149993, 0, 2014, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140700, 0, 2014, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140800, 0, 2014, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20140900, 0, 2014, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20149994, 0, 2014, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20141000, 0, 2014, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20141100, 0, 2014, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20141200, 0, 2014, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150000, 0, 2015, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20159991, 0, 2015, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150100, 0, 2015, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150200, 0, 2015, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150300, 0, 2015, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20159992, 0, 2015, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150400, 0, 2015, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150500, 0, 2015, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150600, 0, 2015, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20159993, 0, 2015, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150700, 0, 2015, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150800, 0, 2015, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20150900, 0, 2015, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20159994, 0, 2015, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20151000, 0, 2015, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20151100, 0, 2015, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20151200, 0, 2015, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160000, 0, 2016, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20169991, 0, 2016, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160100, 0, 2016, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160200, 0, 2016, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160300, 0, 2016, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20169992, 0, 2016, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160400, 0, 2016, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160500, 0, 2016, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160600, 0, 2016, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20169993, 0, 2016, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160700, 0, 2016, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160800, 0, 2016, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20160900, 0, 2016, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20169994, 0, 2016, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20161000, 0, 2016, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20161100, 0, 2016, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20161200, 0, 2016, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170000, 0, 2017, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20179991, 0, 2017, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170100, 0, 2017, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170200, 0, 2017, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170300, 0, 2017, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20179992, 0, 2017, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170400, 0, 2017, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170500, 0, 2017, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170600, 0, 2017, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20179993, 0, 2017, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170700, 0, 2017, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170800, 0, 2017, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20170900, 0, 2017, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20179994, 0, 2017, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20171000, 0, 2017, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20171100, 0, 2017, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20171200, 0, 2017, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180000, 0, 2018, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20189991, 0, 2018, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180100, 0, 2018, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180200, 0, 2018, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180300, 0, 2018, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20189992, 0, 2018, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180400, 0, 2018, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180500, 0, 2018, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180600, 0, 2018, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20189993, 0, 2018, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180700, 0, 2018, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180800, 0, 2018, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20180900, 0, 2018, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20189994, 0, 2018, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20181000, 0, 2018, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20181100, 0, 2018, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20181200, 0, 2018, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190000, 0, 2019, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20199991, 0, 2019, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190100, 0, 2019, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190200, 0, 2019, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190300, 0, 2019, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20199992, 0, 2019, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190400, 0, 2019, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190500, 0, 2019, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190600, 0, 2019, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20199993, 0, 2019, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190700, 0, 2019, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190800, 0, 2019, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20190900, 0, 2019, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20199994, 0, 2019, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20191000, 0, 2019, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20191100, 0, 2019, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20191200, 0, 2019, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200000, 0, 2020, 'Остатки на начало года', 'Остатки на начало года', 0, 'Остатки на начало года');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20209991, 0, 2020, 'Полугодие 1', 'Квартал 1', 91, 'Квартал 1');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200100, 0, 2020, 'Полугодие 1', 'Квартал 1', 1, 'Январь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200200, 0, 2020, 'Полугодие 1', 'Квартал 1', 2, 'Февраль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200300, 0, 2020, 'Полугодие 1', 'Квартал 1', 3, 'Март');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20209992, 0, 2020, 'Полугодие 1', 'Квартал 2', 92, 'Квартал 2');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200400, 0, 2020, 'Полугодие 1', 'Квартал 2', 4, 'Апрель');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200500, 0, 2020, 'Полугодие 1', 'Квартал 2', 5, 'Май');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200600, 0, 2020, 'Полугодие 1', 'Квартал 2', 6, 'Июнь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20209993, 0, 2020, 'Полугодие 2', 'Квартал 3', 93, 'Квартал 3');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200700, 0, 2020, 'Полугодие 2', 'Квартал 3', 7, 'Июль');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200800, 0, 2020, 'Полугодие 2', 'Квартал 3', 8, 'Август');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20200900, 0, 2020, 'Полугодие 2', 'Квартал 3', 9, 'Сентябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20209994, 0, 2020, 'Полугодие 2', 'Квартал 4', 94, 'Квартал 4');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20201000, 0, 2020, 'Полугодие 2', 'Квартал 4', 10, 'Октябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20201100, 0, 2020, 'Полугодие 2', 'Квартал 4', 11, 'Ноябрь');
insert into FX_DATE_YEARMONTH (ID, ROWTYPE, DATEYEAR, DATEHALFYEAR, DATEQUARTER, DATEMONTHID, DATEMONTH)
values (20201200, 0, 2020, 'Полугодие 2', 'Квартал 4', 12, 'Декабрь');

/* End   - 6630 - расширение классификаторов 'период' до 2020 года  - feanor - 28.11.2007 */

go
