//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krista.FM.RIA.Extensions.EO12InvestProjects.Presentation.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krista.FM.RIA.Extensions.EO12InvestProjects.Presentation.Views.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на var SaveProjectAttributes = function () {
        ///    ProjectAttrForm.form.submit({
        ///        waitMsg: &apos;Сохранение...&apos;,
        ///        success: successFormSaveHandler,
        ///        failure: failureFormSaveHandler,
        ///        params: { projId: ID.getValue() }  
        ///        });
        ///};
        ///
        ///
        ///var onTabCloseEventHandler = function (currentTab) {
        ///    if (currentTab.forceClose != undefined &amp;&amp; currentTab.forceClose) {
        ///        return true;
        ///    }
        ///    var tabBody = currentTab.getBody();
        ///    if (tabBody.taskForm.isDirty() || tabBody.gpTaskF [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ProjectDetailView {
            get {
                return ResourceManager.GetString("ProjectDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на var openProjectTab = function (projId, refPart, name) {
        ///    var tabPanel = parent.ProjectsTabPanel;
        ///    var id = &apos;ProjectDetail_&apos; + projId;
        ///    var tab = tabPanel.getComponent(id);
        ///    if (!tab) {
        ///        tab = parent.ProjectsTabPanel.addTab({ id: id,
        ///            title: &apos;Карта инвестиционного проекта - &apos; + name,
        ///            closable: true,
        ///            autoLoad: {
        ///                showMask: true,
        ///                url: &apos;/View/InvProjProjectDetail&apos; + &apos;?projId=&apos; + projId + &apos;&amp;refPart=&apos; + refPart,
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ProjectsListView {
            get {
                return ResourceManager.GetString("ProjectsListView", resourceCulture);
            }
        }
    }
}
