using System;
using System.Collections.Generic;
using System.Text;

namespace Krista.FM.Client.SchemeEditor
{
    public enum Images : int
    {
        Empty = 0,
        SuffixEmpty = 1,
        SuffixLock = 2,
        SuffixCheck1 = 3,
        SuffixCheck2 = 4,
        SuffixCheck3 = 5,
        SuffixUser = 6,
        SuffixPlus = 7,
        SuffixMinus = 8,
        SuffixDelete = 9,
        Folders = 10,
        Folder = 11,
        FolderOpen = 12,
        FolderFile = 13,
        FolderFileOpen = 14,
        Classes = 15,
        Class = 16,
        ClassBlue = 17,
        ClassYellow = 18,
        ClassGreen = 19,
        ClassViolet = 20,
        File = 21,
        Documents = 22,
        Associasions = 23,
        Associasions2 = 24,
        Hierarchy = 25,
        Attributes = 26,
        Attribute = 27,
        AttributeKey = 28,
        AttributeLock = 29,
        AttributeLink = 30,
        AttributeServ = 31,
        Associasion = 32,
        AssociasionBridge = 33,
        Refresh = 34,
        XMLConfigaration = 35,
        Edit = 36,
        ViewChange = 37,
        ApplayChange = 38,
        CancelChange = 39,
        Remove = 40,
        CreatePackage = 41,
        CreateClass = 42,
        CreateAssociation = 43,
        CreateDocument = 44,
        CreateAttribute = 45,
        FixedString = 46,
        AssociateMapping = 47,
        CreateAssociateMapping = 48,
        AssociateRuleMapping = 49,
        CreateAssociateRuleMapping = 50,
        Constant = 51,
        Database = 52,
        Scheme = 53,
        Properties = 54,
        PumpRegistry = 55,
        AssociationMD = 56,
        DataRow = 57,
        GoToObject = 58,
        DataSuppliersLocked = 59,
        ErrorReport = 60,
        View = 61,
        Views = 62,
        UniqueKey = 63,
        UniqueKeys = 64,
        SuffixCheck21 = 65
    }
}
