//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Krista.FM.Server.WebServices
{

    /*[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "FinancialReportServiceBinding", Namespace = "http://services.sibsac.com/")]
    public partial class FinancialReportService : SoapHttpClientProtocol
    {
        private System.Threading.SendOrPostCallback getComparableClassifiersOperationCompleted;

        private System.Threading.SendOrPostCallback getDataClassifiersOperationCompleted;

        private System.Threading.SendOrPostCallback getReportsOperationCompleted;

        /// <remarks/>
        public FinancialReportService()
        {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://portal.sibsac/FinancialReportService/port";
        }

        /// <remarks/>
        public event getComparableClassifiersCompletedEventHandler getComparableClassifiersCompleted;

        /// <remarks/>
        public event getDataClassifiersCompletedEventHandler getDataClassifiersCompleted;

        /// <remarks/>
        public event getReportsCompletedEventHandler getReportsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.sibsac.com//getComparableClassifiers", RequestElementName = "getComparableClassifiersElement", RequestNamespace = "http://services.sibsac.com/types/", ResponseElementName = "getComparableClassifiersResponseElement", ResponseNamespace = "http://services.sibsac.com/types/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public ComparableClassifier[] getComparableClassifiers()
        {
            object[] results = this.Invoke("getComparableClassifiers", new object[0]);
            return ((ComparableClassifier[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetComparableClassifiers(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getComparableClassifiers", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public ComparableClassifier[] EndgetComparableClassifiers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ComparableClassifier[])(results[0]));
        }

        /// <remarks/>
        public void getComparableClassifiersAsync()
        {
            this.getComparableClassifiersAsync(null);
        }

        /// <remarks/>
        public void getComparableClassifiersAsync(object userState)
        {
            if ((this.getComparableClassifiersOperationCompleted == null))
            {
                this.getComparableClassifiersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComparableClassifiersOperationCompleted);
            }
            this.InvokeAsync("getComparableClassifiers", new object[0], this.getComparableClassifiersOperationCompleted, userState);
        }

        private void OngetComparableClassifiersOperationCompleted(object arg)
        {
            if ((this.getComparableClassifiersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComparableClassifiersCompleted(this, new getComparableClassifiersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.sibsac.com//getDataClassifiers", RequestElementName = "getDataClassifiersElement", RequestNamespace = "http://services.sibsac.com/types/", ResponseElementName = "getDataClassifiersResponseElement", ResponseNamespace = "http://services.sibsac.com/types/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DataClassifier[] getDataClassifiers()
        {
            object[] results = this.Invoke("getDataClassifiers", new object[0]);
            return ((DataClassifier[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetDataClassifiers(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getDataClassifiers", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public DataClassifier[] EndgetDataClassifiers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DataClassifier[])(results[0]));
        }

        /// <remarks/>
        public void getDataClassifiersAsync()
        {
            this.getDataClassifiersAsync(null);
        }

        /// <remarks/>
        public void getDataClassifiersAsync(object userState)
        {
            if ((this.getDataClassifiersOperationCompleted == null))
            {
                this.getDataClassifiersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataClassifiersOperationCompleted);
            }
            this.InvokeAsync("getDataClassifiers", new object[0], this.getDataClassifiersOperationCompleted, userState);
        }

        private void OngetDataClassifiersOperationCompleted(object arg)
        {
            if ((this.getDataClassifiersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataClassifiersCompleted(this, new getDataClassifiersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.sibsac.com//getReports", RequestElementName = "getReportsElement", RequestNamespace = "http://services.sibsac.com/types/", ResponseElementName = "getReportsResponseElement", ResponseNamespace = "http://services.sibsac.com/types/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public FinancialReport[] getReports(int year)
        {
            object[] results = this.Invoke("getReports", new object[] {
                    year});
            return ((FinancialReport[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetReports(int year, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getReports", new object[] {
                    year}, callback, asyncState);
        }

        /// <remarks/>
        public FinancialReport[] EndgetReports(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((FinancialReport[])(results[0]));
        }

        /// <remarks/>
        public void getReportsAsync(int year)
        {
            this.getReportsAsync(year, null);
        }

        /// <remarks/>
        public void getReportsAsync(int year, object userState)
        {
            if ((this.getReportsOperationCompleted == null))
            {
                this.getReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReportsOperationCompleted);
            }
            this.InvokeAsync("getReports", new object[] {
                    year}, this.getReportsOperationCompleted, userState);
        }

        private void OngetReportsOperationCompleted(object arg)
        {
            if ((this.getReportsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReportsCompleted(this, new getReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }*/

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.sibsac.com/types/")]
    public partial class ComparableClassifier
    {

        private long recordIdField;

        private long parentIdField;

        private string nameField;

        private string codeField;

        private int typeField;

        /// <remarks/>
        public long recordId
        {
            get
            {
                return this.recordIdField;
            }
            set
            {
                this.recordIdField = value;
            }
        }

        /// <remarks/>
        public long parentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.sibsac.com/types/")]
    public partial class FinancialReport
    {

        private int budgetLevelField;

        private string municipalCodeField;

        private BudgetIndicator[] budgetStatsField;

        private BudgetSummary budgetTotalField;

        /// <remarks/>
        public int budgetLevel
        {
            get
            {
                return this.budgetLevelField;
            }
            set
            {
                this.budgetLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string municipalCode
        {
            get
            {
                return this.municipalCodeField;
            }
            set
            {
                this.municipalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("budgetStats")]
        public BudgetIndicator[] budgetStats
        {
            get
            {
                return this.budgetStatsField;
            }
            set
            {
                this.budgetStatsField = value;
            }
        }

        /// <remarks/>
        public BudgetSummary budgetTotal
        {
            get
            {
                return this.budgetTotalField;
            }
            set
            {
                this.budgetTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.sibsac.com/types/")]
    public partial class DataClassifier
    {

        private long recordIdField;

        private long parentIdField;

        private string nameField;

        private string codeField;

        private int typeField;

        private long[] comparableIdsField;

        /// <remarks/>
        public long recordId
        {
            get
            {
                return this.recordIdField;
            }
            set
            {
                this.recordIdField = value;
            }
        }

        /// <remarks/>
        public long parentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comparableIds")]
        public long[] comparableIds
        {
            get
            {
                return this.comparableIdsField;
            }
            set
            {
                this.comparableIdsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getComparableClassifiersCompletedEventHandler(object sender, getComparableClassifiersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComparableClassifiersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getComparableClassifiersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ComparableClassifier[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ComparableClassifier[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getDataClassifiersCompletedEventHandler(object sender, getDataClassifiersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataClassifiersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getDataClassifiersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DataClassifier[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DataClassifier[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getReportsCompletedEventHandler(object sender, getReportsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public FinancialReport[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((FinancialReport[])(this.results[0]));
            }
        }
    }
}
