//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krista.FM.RIA.Extensions.Consolidation.Presentation.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krista.FM.RIA.Extensions.Consolidation.Presentation.Views.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на function newTaskWindowSubmit() {
        ///    newTaskForm.getForm().submit();
        ///}.
        /// </summary>
        internal static string CollectingTasksView {
            get {
                return ResourceManager.GetString("CollectingTasksView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .x-grid3-hd-inner {
        ///    line-height: 11px; 
        ///    padding-top: 0px;
        ///}
        ///.x-grid-group-hd {
        ///    border-bottom: 1px solid;
        ///    border-bottom-color: #99BBE8;
        ///    padding-top: 0;
        ///}
        ///.x-grid3-cell-inner {
        ///    line-height: 11px;
        ///    padding: 1px 3px 1px 5px;
        ///}.
        /// </summary>
        internal static string TasksViewCss {
            get {
                return ResourceManager.GetString("TasksViewCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///var onTabCloseEventHandler = function (currentTab) {
        ///    if (currentTab.forceClose != undefined &amp;&amp; currentTab.forceClose) {
        ///        return true;
        ///    }
        ///    var tabBody = currentTab.getBody();
        ///    if (tabBody.taskForm.isDirty() || tabBody.gpTaskFiles.isDirty()) {
        ///        Ext.Msg.show({
        ///            title: &apos;Внимание&apos;,
        ///            msg: &apos;При закрытии все несохраненные изменения будут потеряны. Закрыть?&apos;,
        ///            buttons: Ext.Msg.YESNO,
        ///            animEl: &apos;viewportMain&apos;,
        ///            icon: Ext.Mes [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TaskView {
            get {
                return ResourceManager.GetString("TaskView", resourceCulture);
            }
        }
    }
}
