<?xml version="1.0" encoding="utf-8"?>
<styleLibrary office2007ColorScheme="Blue">
  <annotation>
    <lastModified>2010-08-23T10:04:45</lastModified>
  </annotation>
  <styleSets defaultStyleSet="Default">
    <styleSet name="Default" viewStyle="Office2007">
      <componentStyles>
        <componentStyle name="Inbox MonthCalendar">
          <properties>
            <property name="Font" colorCategory="{Default}">Segoe UI, 8.25pt</property>
            <property name="ForeColor" colorCategory="{Default}">Black</property>
            <property name="TitleBackColor" colorCategory="{Default}">173, 209, 255</property>
            <property name="TitleForeColor" colorCategory="{Default}">Black</property>
          </properties>
        </componentStyle>
        <componentStyle name="Inbox Panel">
          <properties>
            <property name="BackColor" colorCategory="{Default}">White</property>
            <property name="Font" colorCategory="{Default}">Segoe UI, 8.25pt</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraCalculator" buttonStyle="FlatBorderless" useFlatMode="True" />
        <componentStyle name="UltraExpandableGroupBox">
          <properties>
            <property name="BorderStyle" colorCategory="{Default}">RectangularSolid</property>
            <property name="ViewStyle" colorCategory="{Default}">VisualStudio2005</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraExplorerBar" useFlatMode="True" />
        <componentStyle name="UltraFormattedTextEditor" viewStyle="Standard" />
        <componentStyle name="UltraGrid" useFlatMode="True" />
        <componentStyle name="UltraTabbedMdiManager">
          <properties>
            <property name="HotTrack" colorCategory="{Default}">True</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraTabControl">
          <properties>
            <property name="UseHotTracking" colorCategory="{Default}">True</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraTabStripControl">
          <properties>
            <property name="UseHotTracking" colorCategory="{Default}">True</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraTree" useFlatMode="True" />
      </componentStyles>
      <styles>
        <style role="Base">
          <states>
            <state name="Normal" themedElementAlpha="Transparent" />
          </states>
        </style>
        <style role="DesktopAlertCloseButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertDropDownButton">
          <states>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertPinButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="ExplorerBarControlArea">
          <states>
            <state name="Normal" backColor="233, 241, 251" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarGroupHeader">
          <states>
            <state name="Normal" borderColor="Transparent" />
          </states>
        </style>
        <style role="GridAddNewBox">
          <states>
            <state name="Normal" backColor="White" borderColor="176, 207, 247" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridAddNewBoxButton">
          <states>
            <state name="Normal" foreColor="96, 96, 96">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridBandHeader">
          <states>
            <state name="Normal" backColor="213, 228, 242" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridCardCaption">
          <states>
            <state name="Normal" backColor="213, 228, 242" backGradientStyle="None" backHatchStyle="None" />
            <state name="Selected" backColor="176, 207, 247" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridCell">
          <states>
            <state name="Normal" borderColor="191, 197, 210" />
            <state name="EditMode">
              <resources>
                <name>GridCell_EditMode</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridColumnHeader">
          <states>
            <state name="Normal">
              <resources>
                <name>GridColumnHeader_Normal</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>GridColumnHeader_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridControlArea">
          <states>
            <state name="Normal" backColor="White" borderColor="191, 197, 210" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridGroupByBox">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridGroupByBoxPrompt">
          <states>
            <state name="Normal" backColor="Transparent" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridRow">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
            <state name="Selected">
              <resources>
                <name>GridRow_Selected</name>
              </resources>
            </state>
            <state name="Active">
              <resources>
                <name>GridRow_Active</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRowSelector">
          <states>
            <state name="Normal" backColor="213, 228, 242" borderColor="191, 197, 210" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridRowSelectorHeader">
          <states>
            <state name="Normal" backColor="213, 228, 242" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="Link">
          <states>
            <state name="HotTracked" foreColor="21, 66, 139" />
          </states>
        </style>
        <style role="ProgressBarFill">
          <states>
            <state name="Normal">
              <resources>
                <name>ProgressBar_Normal</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="ScrollBarTrackSectionVertical">
          <states>
            <state name="Normal" backColor="Transparent" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="StatusBarProgressBar">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ToolbarEditAreaProgressBar">
          <states>
            <state name="Normal" backColor="Transparent" backGradientStyle="None" backHatchStyle="None">
              <resources>
                <name>ProgressBar_Normal</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="ToolTipBalloon">
          <states>
            <state name="Normal" backColor="Office2007.ToolTipGradientDark" borderColor="Office2007.ToolTipBorder" backColor2="Office2007.ToolTipGradientLight" backGradientStyle="Vertical" />
          </states>
        </style>
        <style role="TreeCell">
          <states>
            <state name="Normal" borderColor="222, 229, 239" />
          </states>
        </style>
        <style role="TreeColumnHeader">
          <states>
            <state name="Normal">
              <resources>
                <name>GridColumnHeader_Normal</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraButtonBase" buttonStyle="FlatBorderless">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>Button_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraCalculator">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraCalculatorButton">
          <states>
            <state name="Normal" foreColor="96, 96, 96">
              <resources>
                <name>ButtonOffice2K7Blue_Normal</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>Button_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraFormattedTextEditor">
          <states>
            <state name="Normal" backColor="Transparent" borderColor="158, 182, 206" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraPanel">
          <states>
            <state name="Normal" backColor="Office2007.DockAreaGradientDark" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraProgressBar" borderStyle="Rounded1">
          <states>
            <state name="Normal" borderColor="Office2007.ToolTipBorder" />
          </states>
        </style>
        <style role="ValueListItem">
          <states>
            <state name="Selected" backColor="Office2007.AddRemoveHighlight" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
      </styles>
      <sharedObjects>
        <sharedObject name="ScrollBar">
          <properties>
            <property name="MinimumThumbHeight" colorCategory="{Default}">30</property>
            <property name="MinimumThumbWidth" colorCategory="{Default}">30</property>
            <property name="ViewStyle" colorCategory="{Default}">Outlook2007</property>
          </properties>
        </sharedObject>
      </sharedObjects>
    </styleSet>
  </styleSets>
  <resources>
    <resource name="BackgroundAndBorder" backColor="234, 242, 251" borderColor="176, 202, 235" backGradientStyle="None" backHatchStyle="None" />
    <resource name="Button" foreColor="21, 66, 139" borderColor="Transparent" fontName="Segoe UI" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAALQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABlklEQVRIS63VsS8DYRjH8YfBX+IvUglhMZnYxFCRtAmRMJmYOiBhUQMNQ4fSECpNKno9onWud1RbrZ66u/aa+HmfCAuTPJd8x/fz5u7N814fAFqJF0H/eLrBx8+qgYH+X8Ls0GAfLezoiKdNaJYjGptsU2TrCsXqO87vmqJdmQ7YpnAsi4eah0yxJVrBboNtmlk/R/nFR6bkiHZbccE2Ta2mYTe7uLxvi1aq+mCbJpeTqLQChb+LZtQ7YJsmFg9Re+sp3BPNbgZgm8aiB6g5PVyUPNGsRgC2aWR+D7Y65FS+Idrdkwu2KTQXh6HmIJmriqaVHbBNofAunpodHF+/iGY8u2CbhtUuphq0E60hmq4GjW0aVd/JrPtIF15Fu7FdsE3j0X31Bj5O9ZZoutqAbTUHCXUX+Ti7dUQrWK6ag8TXJBu1jrpJ26Jptvc1ydOrKbVBV92krmia5YNtmlk7hVHvImt4omm2D7ZpLpbBQz1AzvRFKzx2wDZFN3M4ylZgNXqisck28U9/aTuP/xTZyOG7v9az/Qnk6OtnXbV+uQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="Button_combo" foreColor="Transparent" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA3wAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAASElEQVQ4T2N89en3fwZKAcgQSjEDpQaAfTJqCEZE4A2TsNqN/9ExtjAkGLDIhuCKBIKGgDSCDMIXi0QZQigZjBqCmWEHT5gAACKrC4lrrIubAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="Button_combo_hover" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA7gEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABV0lEQVQ4T42QS0sCYRhGZ1z0f1q3adOulvULut9xUxshCFq00agoxEuJhhZ5WdjGCCMqsBshRUQgQkkalbUJDHz6ns2bWot34MDMfOc5DGNXPr9hmSvpH7ZsR5tl2w4+qi6gbqFesyxGiNfTj7OjBHKHMTX0uZOIb2kA1XIelcK+GvrcSSSwPIjqyw2eCwdq6HMnkY3VIbyWLvF4l1ZDnzuJhNZG8FY8xtP1VgMRc9/K7zl97poi74UsShdBNfSbIuH1UXzc76F84hb6XCm00nhOnzv5koh3DLVzD75SvU00RlrP6HMnkahvHDidBaLtf2Dov/f0uZNIzD8BXM0B6Q49xudOItuBSSA/D2Q69RifO4nsBKeA2wUg26XH+NxJZHdzGnhYBHLdeozPnUTiIRMpus1/6dFjfO4kkgw7gdKKCZmfq8X43EkkFXEiE59BJuHSY3zufgCxXXICQCY/YgAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="Button_HotTracked" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAMQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABmklEQVRIS63VSyuEYRjG8Vs2PodPgwU2iCisRLFQbMhhFhKihsIC5ZChhpwih5LJYpCZNIlEDpPJISFhmLlc9zvYsOJ+6794F8/veQ/dPUkApGP6GPKH6+Ul9r0qJSX5h1CdnZokLRMH8PpOgbeIaWqqLa6xPcSj4UTPIbvoqS31Q7uIv54h/hSwjabaUtvv51OfIPbgN01NtaXS7UPs6RDvdxumqam2lLWvIvYYwtvNCls2asUx1ZbSlkW83wcQjcyyGaNmHVNtKXTN89P4EQ172LhRHsdUW/IbpoGzTiCQztKMokVTbcmpn+JNF+GMz010o/9Gi6baklPnBc7dQDCLZRpFi6bakqtvcNEL7OWxXKNo0VRbCvQfhAeAUAkrNooWTbWlyDUHXI4A+xWs3ChaNNXmHCwAkUngsJbVGEWLptrOJONqBjhqZk1G0aLpTHKVex24XgRO2lmbUbRoqi01fZvA7Rpw2sO6jaJFU22eB1vAnS9ReNAuemqLazSIpR0el6/bpqmptuih3+oJ4S81Dgfx1W/r1f4AnTS4cppalG4AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ButtonOffice2K7Blue_Normal" backColor="Transparent" borderColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAALQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABlklEQVRIS63VsS8DYRjH8YfBX+IvUglhMZnYxFCRtAmRMJmYOiBhUQMNQ4fSECpNKno9onWud1RbrZ66u/aa+HmfCAuTPJd8x/fz5u7N814fAFqJF0H/eLrBx8+qgYH+X8Ls0GAfLezoiKdNaJYjGptsU2TrCsXqO87vmqJdmQ7YpnAsi4eah0yxJVrBboNtmlk/R/nFR6bkiHZbccE2Ta2mYTe7uLxvi1aq+mCbJpeTqLQChb+LZtQ7YJsmFg9Re+sp3BPNbgZgm8aiB6g5PVyUPNGsRgC2aWR+D7Y65FS+Idrdkwu2KTQXh6HmIJmriqaVHbBNofAunpodHF+/iGY8u2CbhtUuphq0E60hmq4GjW0aVd/JrPtIF15Fu7FdsE3j0X31Bj5O9ZZoutqAbTUHCXUX+Ti7dUQrWK6ag8TXJBu1jrpJ26Jptvc1ydOrKbVBV92krmia5YNtmlk7hVHvImt4omm2D7ZpLpbBQz1AzvRFKzx2wDZFN3M4ylZgNXqisck28U9/aTuP/xTZyOG7v9az/Qnk6OtnXbV+uQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="DesktopAlertDropDownButton_HotTracked" backColor="255, 231, 162" foreColor="Black" borderColor="255, 189, 105" backGradientStyle="None" backHatchStyle="None" />
    <resource name="gradient_bg" backColor="White" borderColor="Transparent" backColor2="176, 202, 235" backGradientStyle="Vertical" />
    <resource name="GridCell_EditMode" backColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAbgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAA10lEQVRIS+1WSwrCUAxMUTfu3QlexXN5JE9RsOoZxNoPRVBbUFQqaPvGphVxaeC9XQYehEeYSYYsxsNmjnQ4pew5osoQeWQH/R7ReJDTpPSJkuyAVQxcHkBtYA3nElhGAPNT0BT84QKnG8D85G+BqnYh0fH64UfEjUTHyku0m7iEiojcVbvULpEDoma9LrVL5ICoWa9L7RI5IGr+XpfN5Pg7wYtzF0eiIDIo7qLh/m4+XjlBGlC8D7FOgLwRsrURJ0cenLMw85NJZ00RtYq8mq232JmWl/nftwKVzA9lHqMAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="GridColumnHeader_HotTracked" backColor="Transparent" borderColor="242, 149, 54" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAGwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAPwAAABMIBgAAACcx1ZIAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAhElEQVRYR+XDwQoBUQCF4eNJLZSFslAWykJZKAtloSxm4VkQQkYIzWPM3Jk7Y3U8yP/V1/plG4uq+SamVvNZm1r1e2Vq1a+lqRWfC1MrPuamVrzPTK0qnZpa1W1iapXXsalVXkamVjgPTa1wGpha4dg3tYpDz9Qq9l1TK991TK182zb1H6/IWkPV8UmbAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridColumnHeader_Normal" backColor="246, 250, 251" foreColor="64, 94, 131" borderColor="191, 197, 210" imageBackgroundStyle="Stretched" backColor2="211, 219, 233" backGradientStyle="Vertical" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridRow_Active" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAATQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAtklEQVRIS7XDQWfCAQDG4XefLGJ0iNghxg4xdohmFNkOO+3SZaddOnXpVESMKOVPZFO22SxLjH2R97dP8T48JxxGKI39kHTxNSBdfPRJF29PpIvtI+nipUe62DyQLtb3pIvilnSxapMuFteki3GJdHlSJl2enpIuP1dIl2dV0uV5jXR5eUa6XNRJl9fnpMubC9Ll1wbp8u6SdPn9inT5s0m6/N0iXf65IV0+dkiXf7uky393pP8Do3pdmMPchykAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridRow_Selected" foreColor="0, 69, 209" imageBackgroundStyle="Stretched">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAACwEAAAKJUE5HDQoaCgAAAA1JSERSAAAACwAAABQIBgAAAFssx2gAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAdElEQVQ4T5XQOwrCYAAE4fX+9xHBwsLGxkKwESwshIAm8UUiPv6MOcK48HVT7YTSEzu+LVb41FgZ3iesDK8KK+V5xErpD+MhTkq3xwr1FOvPuJmBFJr5GDuhXWCFyxIrXFdY4bbGCvcNVnhssUK3wwrljPUDYL0XRV2kXHAAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ProgressBar_Normal" backColor="Transparent" borderColor="Transparent" backGradientStyle="None" backHatchStyle="None">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAJgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABcIBgAAAAL2z9kAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAj0lEQVQ4T6XUXwoBUQCF8WMLc28ezNiSpUiRkMifNA+WpaSklOYOKVnJca3hO/V7/R5Pp7sbWGR1ezShfapNaNMcTGjVbE1o0axNaJaWJjRJcxMatVMTGj7HJlSceiZUnHMAUHEpTShcSxMKtxwAFO45ACg8KhMKKQcAxVdlQvHdN6H4yQFA8ZsDgP6vTPwAQjc1pbxSJB4AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarArrowDown_HotTracked" borderColor="Transparent" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAmwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABEIBgAAANSvLMQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABBElEQVQ4T2N8/fb9/4WrtjGQDUAGtE9a8P/33/8kY5A+BpABjT2zwJq//CQeg9SD9IENqGqdTJYBIH1gA0rqeskyAKSPOgbkVrTDXRCa2vufEAaFFSgMQPrALsgobkLxgk90/X9cGBbQIANA+sAGpBXWY4SBS2Dhf3SMHEsgA0D6wAakFtT/f/vlz//zD3+gYGu3pP8wjC4HUg/SB/fC2y9//1949BMDG9uEYBUHqYd7Iae87f/7r3//X3n6i2gMUg/SB3YBxQYU1fb8//jt7/+bL34TjUHqQfrALqhsmfT/849//++/+UM0BqkH6QMb0NA98/9XYOIgFYP0gQ1omzifbAwA5np33st0NBQAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ScrollBarArrowDown_Normal" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAALwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABEIBgAAANSvLMQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAmElEQVQ4T2N8/fb9f0F+Xobfv38z/P//n+Hv379gDGKDMAwwMjKCmSAahv/9+8fAADLgz58//79///7/27dv/z9//vz/w4cP/9+/f///3bt3cAzigzBI7uPHj/8/ffoEZo8agCUMQlN7/xPCBAPRJ7r+Py5MdCy4BBb+R8ckR6O1W9J/GCY7HRjbhIATE9kGwFLjqAE0DEQAzKTBrvDOYqsAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarArrowLeft_HotTracked" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAxQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABAIBgAAAPAxlF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABLklEQVQ4T62TzUsCQRjG7U+LbmFnPZv2AW2ou6EFumm6HtoObUXUpS765xRBHTpVRBHUIuFa5n48ve/YpEUFTQ38YHhZfszOPM/YvdtG7K/L3m2i4RyiYu9jpb6FpfIGDGKx2MC8UcVs3sRMzqT9GrSiJdDLNn3roLK+B2vzADGWBBHghx/hmZy7XgDXC9HuDnh8CtHpRei+YChhgUeD7zi+6oE5vekLzu98XDwEv5McXT5jfDKFs1tfTcLHjid0TMTTahIWJNI1TCUNNQkLUtltJDN1NUmHLlkrtTCd21GXyFf6FwnLlH/nc16UL3ZUxEFTfmIpYsnJ9SCtPyZWdqdPFRAEkoh683V3PIrBewFHW8wNZjRq8ZxeFQ3OZE2xXyhYgnzJxnLNwepbi18BxIxmh0TvRLkAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ScrollBarArrowLeft_Normal" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAARwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABAIBgAAAPAxlF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAsElEQVQ4T6WRvQrCMBRGr48m3STO7dzWUVB0dtI30Ffw5SS/DelS+OQWFIekBhI4Uw6H5N7VS2pQ6THGoBRyzqEUstYiB35tyqOcr2itsd60cyTmEwtLKKUg6hMq0c2BmLsY4UDdX7FtzssRFmNIKdEe7mh2t2+EXxFzKRXZX57ojo+yCMezI/8G+/ud5GBzVvwZbHLFwzAgh0r08N5HXQohIIdxHJMe8WUpNE0TSnkDsa2p3p6Lj18AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarArrowRight_HotTracked" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAYwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABAIBgAAAPAxlF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAzElEQVQ4T2N8/fb9fwZKQdvE+f8bumf+r2yZ9L+otud/TnkbGGcUN/1PLaj/n1ZYD2bnVrT/L6nrBeOq1sn/G3tm/W+ftOB/z/Sl/xlAhnz9+f//5x///n/89vf/+68Q/PYLCP/5//vvf7wYxZD7b/78v/ni9/8rT3+B8YVHP/+ff/jj/xegBbgwyAK8hjh5J1PHEN+IEspdAjIkIrWVMu/ADEkunIrVIKLCBNmQvLplGAaRbAi2GCLJEIqimCqxQ3FiIyvFUpx3KM3FADDuZmHb+xfoAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
    </resource>
    <resource name="ScrollBarArrowRight_Normal" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAMAEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABAIBgAAAPAxlF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAmUlEQVQ4T62SPQrDMAyF1at1Dd2zh6yFQOZuPUKv0MuV+hfsxfCKh0DSSqlBMXyL3tPDlnx6vS1Ie0op0EI5Z2ihlBK0UIwRHOduYOucl5xz4Kghl35mtW8/WWvBsYT0453V1z1kjAHHOmSYHqxn6WsOud6eYlBziHTjWj9mJv8GK+mbwe6tWNJ+Vuy9hxYKIUCL+GNbn1J9H96gqct8KjiuAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarArrowUp_HotTracked" borderColor="Transparent" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAjwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABEIBgAAANSvLMQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAA+ElEQVQ4T62TSwsBYRhG+Wu2srcXWSC3cikzyLDAAlmwwcbCD/A3WNhYiVKKaZIht/HyvEVyyRimzu45p+/7asxzWaFWp2sy/CGQKzfpoNHXwDMhkCrUWVZ3+sEeHgfiUsVQAB4HwkLRUADefwLeaO7tCXxC++Xb4A3g8QncofTLgCNQpSuPD4wAPA64AuJTwO6U6JH7CALwOOD0iySrR+qNt4zNHn7LdYM9vNsVZFWj/mRHFqvjI9hhf7uCJ5IlZa3RYLrXDfbw+AQ/B4KJAi03Gg1nB91gD49PEMuUabU90Whx1A328DiQzNdoffmRvgUeB7KlhmHOD7h7GQvxZwkAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ScrollBarArrowUp_Normal" foreColor="Transparent" imageBackgroundStyle="Centered">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAKwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABEIBgAAANSvLMQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAlElEQVQ4T2N8/fb9f0F+Xobfv38z/P//n+Hv379gDGKDMAwwMjKCmSAahv/9+8fAADLgz58//79///7/27dv/z9//vz/w4cP/9+/f///3bt3cAzigzBI7uPHj/8/ffoEZo8aQEQY5NUtAwckWYGYXDj1PwyTbEBEaut/dEx0NPpGlPzHhQmmAyfv5P+E8GhCGmyZCQBrZ8HRbkuUUAAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarThumbHorizontal_HotTracked">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADwIAAAKJUE5HDQoaCgAAAA1JSERSAAAAHQAAABEIBgAAACFRp3QAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABeElEQVRIS92Vy07CQBSG63v5Mia69TVM9BlcGBNNjBc2LFQoFRQalYsWWkAIQopAodwkvQK/MyTAYOJCG7qwyZem6Zn55syZywYAzvfnnFewvc9jczewdrb2bhFMVMBRoVTR0Wq114re7aNQ1bBzEAFHM6TCcLqxgM804YXIiwaWu6yO+/wAlu3OZnNFSgNpQFTueSKmDMASL44glk24EyylWluHIHUQk/ugAYk3wxNi2SKSJc/vDjI1B2NW2tFJZrkuHvLD2YgeK44nUlUHLJLqQv5wf5AWPv2TVmt1HIZUHEfbOBWHOHsyPBFIm2C5zloIKxac8XRZ038pvclZ4L9nqtabOBKaOIn3cZk0EHw1PRGSLbDEijbiJRsuO71apzcT0joIBQuJsv1rRNJmTpJsERZJdUAZT5iaDkcmrlIGhLyFJFnu86C/vpWGC5aS5oKy2Kfzs5em7pKR0B9emZA+VpiSbwI946mPu4j4d8tQIfVx9D71my/K8RThrI2cLgAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarThumbHorizontal_Normal" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA1QAAAAKJUE5HDQoaCgAAAA1JSERSAAAACAAAAAgIBgAAAMQPvosAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAPklEQVQoU2P+//8/w7t/gv9PHtzeiI1mACnIq50EpLDTxCkIy+8Hm4CNBptAuYL4kglgK7DRYCtyoL7ARgMA3EyuF0nTQRoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAGAIAAAKJUE5HDQoaCgAAAA1JSERSAAAAHQAAABEIBgAAACFRp3QAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABgUlEQVRIS72Vy07CQBSG65PqE+jalXHhyrjSF3BnXBrdSKIoFwWEtkC5VUBqb9MLLVABV78zGGo17hiY5EsmadIv55w552wBEDZ+UukKDo4vsLN3tnb2j86ReW5AYMKHQhs2IWvF9TyofR2HJ5cQtndPYdkEmm7AsOzFnTe248EPRpjO5mC+WKqbNmzXhzsMueOHY4STCLP5Z1LqQLccOH4IP5xwJxhF/0kJBgZNqxOA+GPuuMF3IL/Sa1gEfc3Cu+XDJCF3bHcEZzhBNE3UtN56Rb7SQqXxBrmjc6fRtaAOCI02+qmppKhIFxU8yV2UlAF3xLYOhYpZtPHrFWsdpHJVPJZV5KQed1ggcsdYvJVYWpJauL4XcZtv4q6ocicr9vCiaDBpbWNpudrBFZWm6GTKiN2VydJ/JCnWB5DaBqykVG5ruMk2UajRjzQNsmpypdkjUDU6B5Y1Xc7eru7BoO1CPNqnq/Kn15nMCz8g1vuL5SIstwzL9bphQuYT2D7dNF/0jyKfiwUsnQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarThumbHorizontal_Pressed">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAPwIAAAKJUE5HDQoaCgAAAA1JSERSAAAAHQAAABEIBgAAACFRp3QAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABqElEQVRIS93VW0sCQRgG4O1X9IeC6n9EFEVdFXXZXUlQUDdF5m5GRVmBHchEK7c1yorEzmVaah5LV23VEt5mlgYtEoJFL1p4YNj54N3vg9mpA8DV/DHZr9Cis6O+WVd1DR16zG+7wdFAj+8FDk+4qqTLBNYOHtHULYCjHdLAKWuwTIistdHbwmCm7VHwjlec+BR1mt9CaREtMOzGNeP3XsAIogyjlMFZ4L0UKp5HSVgE/G4CtGBGSmtmdGbBLBwpWD3N4Tr8UQrdv6SdxSA4kuoXzR4omi0dK2DW3XlsnedxF/0tVExVLdTyM1Sw+dA6+YB2wzM6jQl0zaU061+WwQxuZjCynYF0XyiN91+GDpFOR61ZOMs7nd15Qps+gI6ZGHoWZQyY05oNb2XATOxlMS2+weUrG++CFFED+0wyxm1Z8NJbRQLZ+4tFlwJmzZ0D5QmVndMVVwq9SzLGSCAtpAXrFWyQ939hvciDEW8LoO5jX0emsYuHweqH01uAm/wxbiIf8JJNb1wbf6IIJvBaRDBZhMUVAM3jDOZDdVGLW0ZtkORx9D6ttU/SIo8H9RnvvAAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarThumbVertical_HotTracked" borderColor="Transparent">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAJgIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAB0IBgAAAEyvh4EAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABj0lEQVRIS+2VyU7CUBiFywu4N/EBeAF3Lty69Q1MXPsaJr6DC2OiiXFgo4nKUJmjMihCATEMgkChTBJaWuB4/2tsJGDCwo2GJl/Sxe3Xe/8251gACBfBHGzenCC9toVZL+vSgrC2vCisr1otAkk2tq+RysvQ+gaMITD4hj4Y4QuD3Q+GBBDLKtjccbLHIXDJypYNSqMFb7KN4IuKaEFH4s3gOCSN42T4M33EijoysgHmAj03JqlWa7h5UuBPd3Gf09lig3P5pHGu4ho86RkkrgcZHol2oyGc1zm2iGpiT2gIsRdIZbYTdqSpO/lnEme0AneiicBzD7dZnXN01zM5f1TZvD6HS5956kz+liTwG8eZSyb/k/lM5jNxRMpmWFPqE4fBjslpqAcxxXKWZe+PeUISnrOJFnzJDnypd+y7ayYH/hYPbTGpsX4aTQ8lkhBirA53vMHZtRdN9sQKSHQW7oGKbCzZqMmo0ah7CLmmoK40OflCyaRYqkCuN9HpqpMNeOyUeCWSeVZo/YlL4g34AauESciYy20VAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
    </resource>
    <resource name="ScrollBarThumbVertical_Normal" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA0wAAAAKJUE5HDQoaCgAAAA1JSERSAAAACAAAAAgIBgAAAMQPvosAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAPElEQVQoU2PMrZ3wn5GBiQEEXnz6C6ZBgJOVkYGXEyj+//9/vJgBZEJe7SQwDsvvh+P4kgn/c4BiQ8IEANJLnu4/FXSLAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAKwIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAB0IBgAAAEyvh4EAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABlElEQVRIS+2Vv07CUBTGy0M4mji5O7iZuPge+gQ6Ozk5OeoLuDkbXSRBVMAAQsuf8q8Ctrbc3tLSAhVw+rz3EgciJiRupk2+9LY993dOTm++EwMgpbJ1JNJVqaNTadVrY31N2tnelPZ2t2IShxyfXkLrmphMZ5jOPoX4OpzM4AUhnMEY1Buh1x+CMPFnudrFydkV2w5JQA6OLtB3XXj+EME4FPKCsQjWdAq1TVBqWXhRDShNC5rhwA0+sH94vgixKYXtMFAwgj8M0ffHsFnWGgPITRN5VUdK7iBX1VHvUJFgKYTYFP1BIKoQ5dOAVTAHpJUOEjmNgdooaT3xPYLMe/L03RP3Dz2JID8PW9STqCermNI/PCcKc376m59YxGYO78HxAhDHxzvxUKy94bnUxmNBw12mjni2iWxFh8VMfKlRG6YFs2fDJA50i6JrEGSKDSRzKuLpMm7uZVwz3abqaJvuIoRPsgeWgf+duRxxtwhFtfEKRdUgV1rIKw0Uyi2UmoaIX5iA8WRRvODlrSoez/fxCfoFDllXKRFD4OoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ScrollBarThumbVertical_Pressed">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAWAIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAB0IBgAAAEyvh4EAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAABwUlEQVRIS+2VSy8DURiGp3+CX2BhZ+UXSMTC3tJChBA7wtKORkLChqh2VKSpInGLmrRoTYW6Vd21Wqp6RUfb0Yvkdc6RTNK4RELCopM8y/Pky5tv3k8FgDMIh+AXD7j9iwj33a+irISrqyrn6msrVRyVVLVoML95jV2fjINADmehPC4jb4ieLMNBcPqycAdz8ETzMDsDqG7TkefgmKS0Rg3xJA6d7QF6MYnZvWcsH2VgJvSvJBkDQgpj9jTmXc+wX2Rx+/gC+q5AYnOHMGaNgLdLMGzLWHBlGD1LSUYvYXg9pUgCD59INJYQdOv30DtSmNqRGV3TkkLfchJGpwzhOAN//N9LRoUgtGsxjItPmNiUGW2TCYXuuSfwYhqLJFxvLP9xsEXJ+2UrZvKHmejIxi78dGOLkvdV8GuZ0LL2ksb/sKhHhVulrGnrU1r1cYV2o4QhS4r17Hn4Cwkr67U4eNsjaf4EmrV3Ci3jUXSaJAwSkYvcp08neZsmTGoyymgcuVJo0gRARR1TEhzebKGkQW2F23cPenso9qMINk5iDN7iU5hYvYFBDGPGmYBW8BdeQJP1FFREx/su9IRq57bYD/gKdOfJviqL3usAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="ScrollBarTrackHorizontal_Normal" imageBackgroundStyle="Stretched">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA2gAAAAKJUE5HDQoaCgAAAA1JSERSAAAAAwAAAA8IBgAAACHqdcQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAQ0lEQVQYV33OIQ7AUAgD0O7+R10GfEhAdqoC85s8UQHp835OKDNDQXdTUFUURAQF7k6BmVEuZd2ssl6fcyjITMpa8AP2cqQYuHRwgQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ScrollBarTrackVertical_Normal" borderColor="Transparent" imageBackgroundStyle="Stretched">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAAgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEgAAAAwIBgAAAG8S7bwAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAa0lEQVQ4T+2SSwqAMAxEk42IIOL9jyimP9ou+hlJoR5CDDwyIWQWQ/i6Dc5jp1IKAaDW2kC1MouZh9Q+6b1TaaBtXYjUqNaKnDNSSgghwFoLYwxE5EVnRXfOOXjvh9b7GCN+Ixn5/Bl97Y8e2FsQ3IoYPLcAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="spacer" backColor="Transparent" borderColor="Transparent" backGradientStyle="None" backHatchStyle="None">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAqQAAAAKJUE5HDQoaCgAAAA1JSERSAAAAAgAAAAIIBgAAAHK2DSQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsNAAALDQHtB8AsAAAAEklEQVQYV2P8//8/AxiAGCAMAE3WCPnXj6AWAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
  </resources>

  <expertBaseElementsColors border="127; 157; 185" panel="193; 216; 240" darkpanel="141; 178; 227"/>
  <gridPropertys>
    <comments>
      <style>
        <colors backColorStart="Info" backColorEnd="Info" borderColor="Black" foreColor="InfoText"/>
        <font sfont="Arial; 9pt"/>
      </style>
      <propertys timerInterval="500" maxWidth="500" isDisplay="true"/>
    </comments>
    <painter>
      <colors highlightColor="242; 192; 104"/>
    </painter>
    <filtersCaptions >
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
      <optionalCellStyle>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="NoWrap" />
      </optionalCellStyle>
    </filtersCaptions>
    <columnsCaptions>
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
    </columnsCaptions>
    <rowsCaptions>
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
    </rowsCaptions>
    <rows>
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
      <memPropNameStyle>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Gray"/>
        <font sfont="Arial; 8pt"/>
      </memPropNameStyle>
      <memPropValueStyle>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 8pt"/>
      </memPropValueStyle>
    </rows>
    <columns>
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
      <memPropNameStyle>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Gray"/>
        <font sfont="Arial; 8pt"/>
      </memPropNameStyle>
      <memPropValueStyle>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 8pt"/>
      </memPropValueStyle>
    </columns>
    <measuresCaptions>
      <style>
        <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
    </measuresCaptions>
    <measuresData>
      <style>
        <colors backColorStart="White" backColorEnd="White" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Far" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </style>
      <totalsStyle>
        <colors backColorStart="LightGray" backColorEnd="LightGray" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Far" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </totalsStyle>
	  <dummyStyle>
        <colors backColorStart="WhiteSmoke" backColorEnd="WhiteSmoke" borderColor="158; 182; 206" foreColor="Black"/>
        <font sfont="Arial; 10pt"/>
        <stringFormat hAligment="Far" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
      </dummyStyle>
    </measuresData>
  </gridPropertys>
  <MDXToolbar>
    <reportElement>
      <elementCaptionStyles columnCount="5">
        <styleGroup name="Стили заголовка отчета">
          <style text="Заголовок" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="Transparent" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Center" vAligment="Center" trimming="EllipsisCharacter"/>
          </style>
          <style text="Заголовок" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Center" vAligment="Center" trimming="EllipsisCharacter"/>
          </style>
          <style text="Заголовок" width="100" height="20">
            <colors backColorStart="228; 236; 247" backColorEnd ="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Center" vAligment="Center" trimming="EllipsisCharacter"/>
          </style>
          <style text="Заголовок" width="100" height="20">
            <colors backColorStart="88; 136; 195" backColorEnd ="88; 136; 195" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Center" vAligment="Center" trimming="EllipsisCharacter"/>
          </style>
          <style text="Заголовок" width="100" height="20">
            <colors backColorStart="192; 80; 77" backColorEnd ="192; 80; 77" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Center" vAligment="Center" trimming="EllipsisCharacter"/>
          </style>
        </styleGroup>
      </elementCaptionStyles>
      <elementCommentStyles columnCount="5">
        <styleGroup name="Стили комментария отчета">
          <style text="Комментарий" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="Transparent" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
          <style text="Комментарий" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
          <style text="Комментарий" width="100" height="20">
            <colors backColorStart="Info" backColorEnd ="Info" borderColor="Transparent" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
          <style text="Комментарий" width="100" height="20">
            <colors backColorStart="Info" backColorEnd ="Info" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
          <style text="Комментарий" width="100" height="20">
            <colors backColorStart="228; 236; 247" backColorEnd ="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
        </styleGroup>
      </elementCommentStyles>
    </reportElement>
    <table>
      <tabs>
        <propertiesTab backColor="245; 243; 247"/>
      </tabs>
      <cellStyles columnCount="6">
        <styleGroup name="Стили">
          <style text="Текст" width="100" height="20">
            <colors backColorStart="228; 236; 247" backColorEnd="228; 236; 247" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="242; 221; 220" backColorEnd="242; 221; 220" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="234; 241; 221" backColorEnd="234; 241; 221" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="229; 224; 236" backColorEnd="229; 224; 236" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="219; 238; 243" backColorEnd="219; 238; 243" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
		  <style>
			<colors backColorStart="WhiteSmoke" backColorEnd="WhiteSmoke" borderColor="158; 182; 206" foreColor="Black"/>
			<font sfont="Arial; 10pt"/>
			<stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
		  </style>
		  
          <style text="Текст" width="100" height="20">
            <colors backColorStart="195; 211; 234" backColorEnd="195; 211; 234" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="230; 185; 184" backColorEnd="230; 185; 184" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="215; 228; 188" backColorEnd="215; 228; 188" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="204; 192; 218" backColorEnd="204; 192; 218" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="182; 221; 232" backColorEnd="182; 221; 232" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
		  <style>
			<colors backColorStart="LightGray" backColorEnd="LightGray" borderColor="158; 182; 206" foreColor="Black"/>
			<font sfont="Arial; 10pt"/>
			<stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
		  </style>

          <style text="Текст" width="100" height="20">
            <colors backColorStart="167; 193; 227" backColorEnd="167; 193; 227" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="217; 151; 149" backColorEnd="217; 151; 149" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="194; 214; 154" backColorEnd="194; 214; 154" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="178; 161; 199" backColorEnd="178; 161; 199" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="147; 205; 221" backColorEnd="147; 205; 221" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
		  <style>
			<colors backColorStart="DarkGray" backColorEnd="DarkGray" borderColor="158; 182; 206" foreColor="White"/>
			<font sfont="Arial; 10pt"/>
			<stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
		  </style>

          <style text="Текст" width="100" height="20">
            <colors backColorStart="88; 136; 195" backColorEnd="88; 136; 195" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="192; 80; 77" backColorEnd="192; 80; 77" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="155; 187; 89" backColorEnd="155; 187; 89" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="128; 100; 162" backColorEnd="128; 100; 162" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="75; 172; 198" backColorEnd="75; 172; 198" borderColor="158; 182; 206" foreColor="White"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
		  <style>
			<colors backColorStart="DimGray" backColorEnd="DimGray" borderColor="158; 182; 206" foreColor="White"/>
			<font sfont="Arial; 10pt"/>
			<stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
		  </style>
        </styleGroup>
		

        <styleGroup name="Стили с градиентом">
          <style text="Текст" width="100" height="20">
            <colors backColorStart="228; 236; 247" backColorEnd="88; 136; 195" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="242; 221; 220" backColorEnd="192; 80; 77" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="234; 241; 221" backColorEnd="155; 187; 89" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="229; 224; 236" backColorEnd="128; 100; 162" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="219; 238; 243" backColorEnd="75; 172; 198" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
          </style>
		  <style>
			<colors backColorStart="WhiteSmoke" backColorEnd="DimGray" borderColor="158; 182; 206" foreColor="Black"/>
			<font sfont="Arial; 10pt"/>
			<stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter" formatFlags="LineLimit" />
		  </style>
        </styleGroup>

        <styleGroup name="Без заливки">
          <style text="Текст" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="Transparent" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
          <style text="Текст" width="100" height="20">
            <colors backColorStart="White" backColorEnd ="White" borderColor="158; 182; 206" foreColor="Black"/>
            <font sfont="Arial; 10pt"/>
            <stringFormat hAligment="Near" vAligment="Near" trimming="EllipsisCharacter"/>
          </style>
        </styleGroup>
      </cellStyles>
    </table>
    <chart>
      <tabs>
        <propertiesTab backColor="244; 240; 238"/>
      </tabs>
    </chart>
  </MDXToolbar>
</styleLibrary>