//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krista.FM.Client.ViewObjects.FinSourcePlanningUI.Gui.Wizards {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValutaCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValutaCodes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krista.FM.Client.ViewObjects.FinSourcePlanningUI.Gui.Wizards.ValutaCodes", typeof(ValutaCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 36.
        /// </summary>
        internal static string R01010 {
            get {
                return ResourceManager.GetString("R01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 826.
        /// </summary>
        internal static string R01035 {
            get {
                return ResourceManager.GetString("R01035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 974.
        /// </summary>
        internal static string R01090 {
            get {
                return ResourceManager.GetString("R01090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 208.
        /// </summary>
        internal static string R01215 {
            get {
                return ResourceManager.GetString("R01215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 840.
        /// </summary>
        internal static string R01235 {
            get {
                return ResourceManager.GetString("R01235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 978.
        /// </summary>
        internal static string R01239 {
            get {
                return ResourceManager.GetString("R01239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 352.
        /// </summary>
        internal static string R01310 {
            get {
                return ResourceManager.GetString("R01310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 398.
        /// </summary>
        internal static string R01335 {
            get {
                return ResourceManager.GetString("R01335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 124.
        /// </summary>
        internal static string R01350 {
            get {
                return ResourceManager.GetString("R01350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 156.
        /// </summary>
        internal static string R01375 {
            get {
                return ResourceManager.GetString("R01375", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 532.
        /// </summary>
        internal static string R01523 {
            get {
                return ResourceManager.GetString("R01523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 578.
        /// </summary>
        internal static string R01535 {
            get {
                return ResourceManager.GetString("R01535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 702.
        /// </summary>
        internal static string R01625 {
            get {
                return ResourceManager.GetString("R01625", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 949.
        /// </summary>
        internal static string R01700J {
            get {
                return ResourceManager.GetString("R01700J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 980.
        /// </summary>
        internal static string R01720 {
            get {
                return ResourceManager.GetString("R01720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 752.
        /// </summary>
        internal static string R01770 {
            get {
                return ResourceManager.GetString("R01770", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 392.
        /// </summary>
        internal static string R01820 {
            get {
                return ResourceManager.GetString("R01820", resourceCulture);
            }
        }
    }
}
