//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krista.FM.Server.Scheme.ScriptingEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeywordOracleSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeywordOracleSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krista.FM.Server.Scheme.ScriptingEngine.KeywordOracleSQL", typeof(KeywordOracleSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFTER.
        /// </summary>
        internal static string AFTER {
            get {
                return ResourceManager.GetString("AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLOCATE.
        /// </summary>
        internal static string ALLOCATE {
            get {
                return ResourceManager.GetString("ALLOCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER.
        /// </summary>
        internal static string ALTER {
            get {
                return ResourceManager.GetString("ALTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE.
        /// </summary>
        internal static string ANALYZE {
            get {
                return ResourceManager.GetString("ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANY.
        /// </summary>
        internal static string ANY {
            get {
                return ResourceManager.GetString("ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVE.
        /// </summary>
        internal static string ARCHIVE {
            get {
                return ResourceManager.GetString("ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVELOG.
        /// </summary>
        internal static string ARCHIVELOG {
            get {
                return ResourceManager.GetString("ARCHIVELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        internal static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string ASC {
            get {
                return ResourceManager.GetString("ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION.
        /// </summary>
        internal static string AUTHORIZATION {
            get {
                return ResourceManager.GetString("AUTHORIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string AVG {
            get {
                return ResourceManager.GetString("AVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP.
        /// </summary>
        internal static string BACKUP {
            get {
                return ResourceManager.GetString("BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BECOME.
        /// </summary>
        internal static string BECOME {
            get {
                return ResourceManager.GetString("BECOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEFORE.
        /// </summary>
        internal static string BEFORE {
            get {
                return ResourceManager.GetString("BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN.
        /// </summary>
        internal static string BEGIN {
            get {
                return ResourceManager.GetString("BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN.
        /// </summary>
        internal static string BETWEEN {
            get {
                return ResourceManager.GetString("BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOK.
        /// </summary>
        internal static string BLOK {
            get {
                return ResourceManager.GetString("BLOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY.
        /// </summary>
        internal static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAK.
        /// </summary>
        internal static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE.
        /// </summary>
        internal static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULK.
        /// </summary>
        internal static string BULK {
            get {
                return ResourceManager.GetString("BULK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY.
        /// </summary>
        internal static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CACHE.
        /// </summary>
        internal static string CACHE {
            get {
                return ResourceManager.GetString("CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASCADE.
        /// </summary>
        internal static string CASCADE {
            get {
                return ResourceManager.GetString("CASCADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE.
        /// </summary>
        internal static string CASE {
            get {
                return ResourceManager.GetString("CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE.
        /// </summary>
        internal static string CHANGE {
            get {
                return ResourceManager.GetString("CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARACTER.
        /// </summary>
        internal static string CHARACTER {
            get {
                return ResourceManager.GetString("CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK.
        /// </summary>
        internal static string CHECK {
            get {
                return ResourceManager.GetString("CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKPOINT.
        /// </summary>
        internal static string CHECKPOINT {
            get {
                return ResourceManager.GetString("CHECKPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLUSTERED.
        /// </summary>
        internal static string CLUSTERED {
            get {
                return ResourceManager.GetString("CLUSTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COALESCE.
        /// </summary>
        internal static string COALESCE {
            get {
                return ResourceManager.GetString("COALESCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLATE.
        /// </summary>
        internal static string COLLATE {
            get {
                return ResourceManager.GetString("COLLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLUMN.
        /// </summary>
        internal static string COLUMN {
            get {
                return ResourceManager.GetString("COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMIT.
        /// </summary>
        internal static string COMMIT {
            get {
                return ResourceManager.GetString("COMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTE.
        /// </summary>
        internal static string COMPUTE {
            get {
                return ResourceManager.GetString("COMPUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTRAINT.
        /// </summary>
        internal static string CONSTRAINT {
            get {
                return ResourceManager.GetString("CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTAINS.
        /// </summary>
        internal static string CONTAINS {
            get {
                return ResourceManager.GetString("CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTAINSTABLE.
        /// </summary>
        internal static string CONTAINSTABLE {
            get {
                return ResourceManager.GetString("CONTAINSTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENTS.
        /// </summary>
        internal static string CONTENTS {
            get {
                return ResourceManager.GetString("CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLFILE.
        /// </summary>
        internal static string CONTROLFILE {
            get {
                return ResourceManager.GetString("CONTROLFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT.
        /// </summary>
        internal static string CONVERT {
            get {
                return ResourceManager.GetString("CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSS.
        /// </summary>
        internal static string CROSS {
            get {
                return ResourceManager.GetString("CROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT.
        /// </summary>
        internal static string CURRENT {
            get {
                return ResourceManager.GetString("CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT_DATE.
        /// </summary>
        internal static string CURRENT_DATE {
            get {
                return ResourceManager.GetString("CURRENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT_TIME.
        /// </summary>
        internal static string CURRENT_TIME {
            get {
                return ResourceManager.GetString("CURRENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT_TIMESTAMP.
        /// </summary>
        internal static string CURRENT_TIMESTAMP {
            get {
                return ResourceManager.GetString("CURRENT_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT_USER.
        /// </summary>
        internal static string CURRENT_USER {
            get {
                return ResourceManager.GetString("CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURSOR.
        /// </summary>
        internal static string CURSOR {
            get {
                return ResourceManager.GetString("CURSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYCLE.
        /// </summary>
        internal static string CYCLE {
            get {
                return ResourceManager.GetString("CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        internal static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATAFILE.
        /// </summary>
        internal static string DATAFILE {
            get {
                return ResourceManager.GetString("DATAFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBCC.
        /// </summary>
        internal static string DBCC {
            get {
                return ResourceManager.GetString("DBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEALLOCATE.
        /// </summary>
        internal static string DEALLOCATE {
            get {
                return ResourceManager.GetString("DEALLOCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE.
        /// </summary>
        internal static string DECLARE {
            get {
                return ResourceManager.GetString("DECLARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENY.
        /// </summary>
        internal static string DENY {
            get {
                return ResourceManager.GetString("DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLE.
        /// </summary>
        internal static string DISABLE {
            get {
                return ResourceManager.GetString("DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISK.
        /// </summary>
        internal static string DISK {
            get {
                return ResourceManager.GetString("DISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISMOUNT.
        /// </summary>
        internal static string DISMOUNT {
            get {
                return ResourceManager.GetString("DISMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTINCT.
        /// </summary>
        internal static string DISTINCT {
            get {
                return ResourceManager.GetString("DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUTED.
        /// </summary>
        internal static string DISTRIBUTED {
            get {
                return ResourceManager.GetString("DISTRIBUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLE.
        /// </summary>
        internal static string DOUBLE {
            get {
                return ResourceManager.GetString("DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP.
        /// </summary>
        internal static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMMY.
        /// </summary>
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMP.
        /// </summary>
        internal static string DUMP {
            get {
                return ResourceManager.GetString("DUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EACH.
        /// </summary>
        internal static string EACH {
            get {
                return ResourceManager.GetString("EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELSE.
        /// </summary>
        internal static string ELSE {
            get {
                return ResourceManager.GetString("ELSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLE.
        /// </summary>
        internal static string ENABLE {
            get {
                return ResourceManager.GetString("ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRLVL.
        /// </summary>
        internal static string ERRLVL {
            get {
                return ResourceManager.GetString("ERRLVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESCAPE.
        /// </summary>
        internal static string ESCAPE {
            get {
                return ResourceManager.GetString("ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        internal static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPT.
        /// </summary>
        internal static string EXCEPT {
            get {
                return ResourceManager.GetString("EXCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTIONS.
        /// </summary>
        internal static string EXCEPTIONS {
            get {
                return ResourceManager.GetString("EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string EXEC {
            get {
                return ResourceManager.GetString("EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE.
        /// </summary>
        internal static string EXECUTE {
            get {
                return ResourceManager.GetString("EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXISTS.
        /// </summary>
        internal static string EXISTS {
            get {
                return ResourceManager.GetString("EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLAIN.
        /// </summary>
        internal static string EXPLAIN {
            get {
                return ResourceManager.GetString("EXPLAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTENT.
        /// </summary>
        internal static string EXTENT {
            get {
                return ResourceManager.GetString("EXTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNALLY.
        /// </summary>
        internal static string EXTERNALLY {
            get {
                return ResourceManager.GetString("EXTERNALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FETCH.
        /// </summary>
        internal static string FETCH {
            get {
                return ResourceManager.GetString("FETCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILLFACTOR.
        /// </summary>
        internal static string FILLFACTOR {
            get {
                return ResourceManager.GetString("FILLFACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLUSH.
        /// </summary>
        internal static string FLUSH {
            get {
                return ResourceManager.GetString("FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR.
        /// </summary>
        internal static string FOR {
            get {
                return ResourceManager.GetString("FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCE.
        /// </summary>
        internal static string FORCE {
            get {
                return ResourceManager.GetString("FORCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOREIGN.
        /// </summary>
        internal static string FOREIGN {
            get {
                return ResourceManager.GetString("FOREIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOUND.
        /// </summary>
        internal static string FOUND {
            get {
                return ResourceManager.GetString("FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE LIST.
        /// </summary>
        internal static string FREE_LIST {
            get {
                return ResourceManager.GetString("FREE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREETEXT.
        /// </summary>
        internal static string FREETEXT {
            get {
                return ResourceManager.GetString("FREETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREETEXTTABLE.
        /// </summary>
        internal static string FREETEXTTABLE {
            get {
                return ResourceManager.GetString("FREETEXTTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL.
        /// </summary>
        internal static string FULL {
            get {
                return ResourceManager.GetString("FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUNCTION.
        /// </summary>
        internal static string FUNCTION {
            get {
                return ResourceManager.GetString("FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOTO.
        /// </summary>
        internal static string GOTO {
            get {
                return ResourceManager.GetString("GOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANT.
        /// </summary>
        internal static string GRANT {
            get {
                return ResourceManager.GetString("GRANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP.
        /// </summary>
        internal static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUPS.
        /// </summary>
        internal static string GROUPS {
            get {
                return ResourceManager.GetString("GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING.
        /// </summary>
        internal static string HAVING {
            get {
                return ResourceManager.GetString("HAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLDLOCK.
        /// </summary>
        internal static string HOLDLOCK {
            get {
                return ResourceManager.GetString("HOLDLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY.
        /// </summary>
        internal static string IDENTITY {
            get {
                return ResourceManager.GetString("IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY_INSERT.
        /// </summary>
        internal static string IDENTITY_INSERT {
            get {
                return ResourceManager.GetString("IDENTITY_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITYCOL.
        /// </summary>
        internal static string IDENTITYCOL {
            get {
                return ResourceManager.GetString("IDENTITYCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF.
        /// </summary>
        internal static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCLUDING.
        /// </summary>
        internal static string INCLUDING {
            get {
                return ResourceManager.GetString("INCLUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDEX.
        /// </summary>
        internal static string INDEX {
            get {
                return ResourceManager.GetString("INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDICATOR.
        /// </summary>
        internal static string INDICATOR {
            get {
                return ResourceManager.GetString("INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INI TRANS.
        /// </summary>
        internal static string INI_TRANS {
            get {
                return ResourceManager.GetString("INI_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER.
        /// </summary>
        internal static string INNER {
            get {
                return ResourceManager.GetString("INNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTANCE.
        /// </summary>
        internal static string INSTANCE {
            get {
                return ResourceManager.GetString("INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERSECT.
        /// </summary>
        internal static string INTERSECT {
            get {
                return ResourceManager.GetString("INTERSECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTO.
        /// </summary>
        internal static string INTO {
            get {
                return ResourceManager.GetString("INTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        internal static string JOIN {
            get {
                return ResourceManager.GetString("JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY.
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KILL.
        /// </summary>
        internal static string KILL {
            get {
                return ResourceManager.GetString("KILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAYER.
        /// </summary>
        internal static string LAYER {
            get {
                return ResourceManager.GetString("LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        internal static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIKE.
        /// </summary>
        internal static string LIKE {
            get {
                return ResourceManager.GetString("LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINENO.
        /// </summary>
        internal static string LINENO {
            get {
                return ResourceManager.GetString("LINENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK.
        /// </summary>
        internal static string LINK {
            get {
                return ResourceManager.GetString("LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTS.
        /// </summary>
        internal static string LISTS {
            get {
                return ResourceManager.GetString("LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        internal static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGFILE.
        /// </summary>
        internal static string LOGFILE {
            get {
                return ResourceManager.GetString("LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        internal static string MANUAL {
            get {
                return ResourceManager.GetString("MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXDATAFILES.
        /// </summary>
        internal static string MAXDATAFILES {
            get {
                return ResourceManager.GetString("MAXDATAFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXINISTANCES.
        /// </summary>
        internal static string MAXINISTANCES {
            get {
                return ResourceManager.GetString("MAXINISTANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATIONAL.
        /// </summary>
        internal static string NATIONAL {
            get {
                return ResourceManager.GetString("NATIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOCHECK.
        /// </summary>
        internal static string NOCHECK {
            get {
                return ResourceManager.GetString("NOCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONCLUSTERED.
        /// </summary>
        internal static string NONCLUSTERED {
            get {
                return ResourceManager.GetString("NONCLUSTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOORDER.
        /// </summary>
        internal static string NOORDER {
            get {
                return ResourceManager.GetString("NOORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORESETLOGS.
        /// </summary>
        internal static string NORESETLOGS {
            get {
                return ResourceManager.GetString("NORESETLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMAL.
        /// </summary>
        internal static string NORMAL {
            get {
                return ResourceManager.GetString("NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOSORT.
        /// </summary>
        internal static string NOSORT {
            get {
                return ResourceManager.GetString("NOSORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        internal static string NOT {
            get {
                return ResourceManager.GetString("NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NULL {
            get {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULLIF.
        /// </summary>
        internal static string NULLIF {
            get {
                return ResourceManager.GetString("NULLIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERIC.
        /// </summary>
        internal static string NUMERIC {
            get {
                return ResourceManager.GetString("NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OF.
        /// </summary>
        internal static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFSETS.
        /// </summary>
        internal static string OFFSETS {
            get {
                return ResourceManager.GetString("OFFSETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD.
        /// </summary>
        internal static string OLD {
            get {
                return ResourceManager.GetString("OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLY.
        /// </summary>
        internal static string ONLY {
            get {
                return ResourceManager.GetString("ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENDATASOURCE.
        /// </summary>
        internal static string OPENDATASOURCE {
            get {
                return ResourceManager.GetString("OPENDATASOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENQUERY.
        /// </summary>
        internal static string OPENQUERY {
            get {
                return ResourceManager.GetString("OPENQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENROWSET.
        /// </summary>
        internal static string OPENROWSET {
            get {
                return ResourceManager.GetString("OPENROWSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENXML.
        /// </summary>
        internal static string OPENXML {
            get {
                return ResourceManager.GetString("OPENXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIMAL.
        /// </summary>
        internal static string OPTIMAL {
            get {
                return ResourceManager.GetString("OPTIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTION.
        /// </summary>
        internal static string OPTION {
            get {
                return ResourceManager.GetString("OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER.
        /// </summary>
        internal static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTER.
        /// </summary>
        internal static string OUTER {
            get {
                return ResourceManager.GetString("OUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER.
        /// </summary>
        internal static string OVER {
            get {
                return ResourceManager.GetString("OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWN.
        /// </summary>
        internal static string OWN {
            get {
                return ResourceManager.GetString("OWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKAGE.
        /// </summary>
        internal static string PACKAGE {
            get {
                return ResourceManager.GetString("PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARALLEL.
        /// </summary>
        internal static string PARALLEL {
            get {
                return ResourceManager.GetString("PARALLEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENT.
        /// </summary>
        internal static string PERCENT {
            get {
                return ResourceManager.GetString("PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN.
        /// </summary>
        internal static string PLAN {
            get {
                return ResourceManager.GetString("PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECISION.
        /// </summary>
        internal static string PRECISION {
            get {
                return ResourceManager.GetString("PRECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY.
        /// </summary>
        internal static string PRIMARY {
            get {
                return ResourceManager.GetString("PRIMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT.
        /// </summary>
        internal static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE.
        /// </summary>
        internal static string PRIVATE {
            get {
                return ResourceManager.GetString("PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROC.
        /// </summary>
        internal static string PROC {
            get {
                return ResourceManager.GetString("PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEDURE.
        /// </summary>
        internal static string PROCEDURE {
            get {
                return ResourceManager.GetString("PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC.
        /// </summary>
        internal static string PUBLIC {
            get {
                return ResourceManager.GetString("PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTA.
        /// </summary>
        internal static string QUOTA {
            get {
                return ResourceManager.GetString("QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAISERROR.
        /// </summary>
        internal static string RAISERROR {
            get {
                return ResourceManager.GetString("RAISERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ.
        /// </summary>
        internal static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READTEXT.
        /// </summary>
        internal static string READTEXT {
            get {
                return ResourceManager.GetString("READTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL.
        /// </summary>
        internal static string REAL {
            get {
                return ResourceManager.GetString("REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECONFIGURE.
        /// </summary>
        internal static string RECONFIGURE {
            get {
                return ResourceManager.GetString("RECONFIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER.
        /// </summary>
        internal static string RECOVER {
            get {
                return ResourceManager.GetString("RECOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        internal static string REFERENCES {
            get {
                return ResourceManager.GetString("REFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCING.
        /// </summary>
        internal static string REFERENCING {
            get {
                return ResourceManager.GetString("REFERENCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPLICATION.
        /// </summary>
        internal static string REPLICATION {
            get {
                return ResourceManager.GetString("REPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESETLOGS.
        /// </summary>
        internal static string RESETLOGS {
            get {
                return ResourceManager.GetString("RESETLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTORE.
        /// </summary>
        internal static string RESTORE {
            get {
                return ResourceManager.GetString("RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTRICT.
        /// </summary>
        internal static string RESTRICT {
            get {
                return ResourceManager.GetString("RESTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTRICTED.
        /// </summary>
        internal static string RESTRICTED {
            get {
                return ResourceManager.GetString("RESTRICTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN.
        /// </summary>
        internal static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REUSE.
        /// </summary>
        internal static string REUSE {
            get {
                return ResourceManager.GetString("REUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVOKE.
        /// </summary>
        internal static string REVOKE {
            get {
                return ResourceManager.GetString("REVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLE.
        /// </summary>
        internal static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLLBACK.
        /// </summary>
        internal static string ROLLBACK {
            get {
                return ResourceManager.GetString("ROLLBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROWCOUNT.
        /// </summary>
        internal static string ROWCOUNT {
            get {
                return ResourceManager.GetString("ROWCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROWGUIDCOL.
        /// </summary>
        internal static string ROWGUIDCOL {
            get {
                return ResourceManager.GetString("ROWGUIDCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULE.
        /// </summary>
        internal static string RULE {
            get {
                return ResourceManager.GetString("RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVEPOINT.
        /// </summary>
        internal static string SAVEPOINT {
            get {
                return ResourceManager.GetString("SAVEPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEMA.
        /// </summary>
        internal static string SCHEMA {
            get {
                return ResourceManager.GetString("SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTION.
        /// </summary>
        internal static string SECTION {
            get {
                return ResourceManager.GetString("SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT.
        /// </summary>
        internal static string SEGMENT {
            get {
                return ResourceManager.GetString("SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCE.
        /// </summary>
        internal static string SEQUENCE {
            get {
                return ResourceManager.GetString("SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESSION_USER.
        /// </summary>
        internal static string SESSION_USER {
            get {
                return ResourceManager.GetString("SESSION_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET.
        /// </summary>
        internal static string SET {
            get {
                return ResourceManager.GetString("SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETUSER.
        /// </summary>
        internal static string SETUSER {
            get {
                return ResourceManager.GetString("SETUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARED.
        /// </summary>
        internal static string SHARED {
            get {
                return ResourceManager.GetString("SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHUTDOWN.
        /// </summary>
        internal static string SHUTDOWN {
            get {
                return ResourceManager.GetString("SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNAPSHOT.
        /// </summary>
        internal static string SNAPSHOT {
            get {
                return ResourceManager.GetString("SNAPSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOME.
        /// </summary>
        internal static string SOME {
            get {
                return ResourceManager.GetString("SOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT.
        /// </summary>
        internal static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLERROR.
        /// </summary>
        internal static string SQLERROR {
            get {
                return ResourceManager.GetString("SQLERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATEMENT_ID.
        /// </summary>
        internal static string STATEMENT_ID {
            get {
                return ResourceManager.GetString("STATEMENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORAGE.
        /// </summary>
        internal static string STORAGE {
            get {
                return ResourceManager.GetString("STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string SUM {
            get {
                return ResourceManager.GetString("SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITCH.
        /// </summary>
        internal static string SWITCH {
            get {
                return ResourceManager.GetString("SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        internal static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM_USER.
        /// </summary>
        internal static string SYSTEM_USER {
            get {
                return ResourceManager.GetString("SYSTEM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLES.
        /// </summary>
        internal static string TABLES {
            get {
                return ResourceManager.GetString("TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLESPACE.
        /// </summary>
        internal static string TABLESPACE {
            get {
                return ResourceManager.GetString("TABLESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPORARY.
        /// </summary>
        internal static string TEMPORARY {
            get {
                return ResourceManager.GetString("TEMPORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTSIZE.
        /// </summary>
        internal static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEN.
        /// </summary>
        internal static string THEN {
            get {
                return ResourceManager.GetString("THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREAD.
        /// </summary>
        internal static string THREAD {
            get {
                return ResourceManager.GetString("THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        internal static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        internal static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACING.
        /// </summary>
        internal static string TRACING {
            get {
                return ResourceManager.GetString("TRACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAN.
        /// </summary>
        internal static string TRAN {
            get {
                return ResourceManager.GetString("TRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTION.
        /// </summary>
        internal static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIGGER.
        /// </summary>
        internal static string TRIGGER {
            get {
                return ResourceManager.GetString("TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIGGERS.
        /// </summary>
        internal static string TRIGGERS {
            get {
                return ResourceManager.GetString("TRIGGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNCATE.
        /// </summary>
        internal static string TRUNCATE {
            get {
                return ResourceManager.GetString("TRUNCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSEQUAL.
        /// </summary>
        internal static string TSEQUAL {
            get {
                return ResourceManager.GetString("TSEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDER.
        /// </summary>
        internal static string UNDER {
            get {
                return ResourceManager.GetString("UNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNION.
        /// </summary>
        internal static string UNION {
            get {
                return ResourceManager.GetString("UNION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUE.
        /// </summary>
        internal static string UNIQUE {
            get {
                return ResourceManager.GetString("UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLIMITED.
        /// </summary>
        internal static string UNLIMITED {
            get {
                return ResourceManager.GetString("UNLIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNTIL.
        /// </summary>
        internal static string UNTIL {
            get {
                return ResourceManager.GetString("UNTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATETEXT.
        /// </summary>
        internal static string UPDATETEXT {
            get {
                return ResourceManager.GetString("UPDATETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE.
        /// </summary>
        internal static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUES.
        /// </summary>
        internal static string VALUES {
            get {
                return ResourceManager.GetString("VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARYING.
        /// </summary>
        internal static string VARYING {
            get {
                return ResourceManager.GetString("VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITFOR.
        /// </summary>
        internal static string WAITFOR {
            get {
                return ResourceManager.GetString("WAITFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN.
        /// </summary>
        internal static string WHEN {
            get {
                return ResourceManager.GetString("WHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        internal static string WHERE {
            get {
                return ResourceManager.GetString("WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHILE.
        /// </summary>
        internal static string WHILE {
            get {
                return ResourceManager.GetString("WHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH.
        /// </summary>
        internal static string WITH {
            get {
                return ResourceManager.GetString("WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK.
        /// </summary>
        internal static string WORK {
            get {
                return ResourceManager.GetString("WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITE.
        /// </summary>
        internal static string WRITE {
            get {
                return ResourceManager.GetString("WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITETEXT.
        /// </summary>
        internal static string WRITETEXT {
            get {
                return ResourceManager.GetString("WRITETEXT", resourceCulture);
            }
        }
    }
}
