print N'Вставляем данные'
GO

INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (0, 'Выплаты по расходам на закупку товаров, работ, услуг всего', '0001', 1)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (1, 'в том числе: на оплату контрактов заключенных до начала очередного финансового года', '1001', 1)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (2, 'на закупку товаров работ, услуг по году начала закупки', '2001', 1)

INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (3, 'Поступления от доходов, всего:', '100', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (4, 'в том числе: доходы от собственности', '110', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (5, 'доходы от оказания услуг, работ', '120', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (6, 'доходы от штрафов, пеней, иных сумм принудительного изъятия', '130', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (7, 'безвозмездные поступления от наднациональных организаций, правительств иностранных государств, международных финансовых организаций', '140', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (8, 'иные субсидии, предоставленные из бюджета', '150', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (9, 'прочие доходы', '160', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (10, 'доходы от операций с активами', '180', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (11, 'Выплаты по расходам, всего:', '200', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (12, 'в том числе на: выплаты персоналу всего:', '210', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (13, 'из них: оплата труда и начисления на выплаты по оплате труда', '211', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (14, 'социальные и иные выплаты населению, всего', '220', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (15, 'из них: уплату налогов, сборов и иных платежей, всего', '230', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (16, 'из них: безвозмездные перечисления организациям', '240', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (17, 'прочие расходы (кроме расходов на закупку товаров, работ, услуг)', '250', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (18, 'расходы на закупку товаров, работ, услуг, всего', '260', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (19, 'Поступление финансовых активов, всего:', '300', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (20, 'из них: увеличение остатков средств', '310', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (21, 'прочие поступления', '320', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (22, 'Выбытие финансовых активов, всего', '400', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (23, 'Из них: уменьшение остатков средств', '410', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (24, 'прочие выбытия', '420', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (25, 'Остаток средств на начало года', '500', 0)
INSERT INTO [DV].[t_F_IndicatorsPfhd]([ID],[Name],[Code],[Detail])
VALUES (26, 'Остаток средств на конец года', '600', 0)
GO


